#!/usr/bin/env python3
"""Verify (or refresh) the cross-repo shared-artifact manifest.

Four files are maintained as byte-identical copies in ``gpu-reservation-app``
and ``gpu-reservation-controller``.  ``docs/SHARED-ARTIFACTS.sha256`` records the
SHA-256 of each; this script is the only thing that reads or writes it, and
``tests/test_shared_artifacts.py`` runs ``--check``.

An identical copy of this script lives at this same path in the sibling repo —
only ``_ARTIFACTS`` differs, because the two repos keep two of the four files at
different paths.  See ``docs/SHARED-ARTIFACTS.md`` for the rationale and for the
procedure when one of these files legitimately changes.

Usage::

    python scripts/sync_shared_artifacts.py --check    # exit 1 on mismatch
    python scripts/sync_shared_artifacts.py --update   # rewrite the manifest
    python scripts/sync_shared_artifacts.py --print    # hashes on stdout
"""

from __future__ import annotations

import argparse
import hashlib
import pathlib
import sys

_REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
_MANIFEST = _REPO_ROOT / "docs" / "SHARED-ARTIFACTS.sha256"

# logical name -> path in THIS repo.  The logical name is what the sibling repo
# keys on, so the two manifests compare equal even though two of the four files
# live at different paths on each side.
_ARTIFACTS = {
    "log_fields.py": "app/log_fields.py",
    "LOG-FIELDS.md": "docs/LOG-FIELDS.md",
    "RESERVATION-API.md": "docs/RESERVATION-API.md",
    "SCHEDULING.md": "docs/SCHEDULING.md",
}

_HEADER = """\
# Shared-artifact manifest — SHA-256 of each file kept byte-identical with the
# sibling repository (gpu-reservation-app <-> gpu-reservation-controller).
#
# Generated by scripts/sync_shared_artifacts.py --update.  Do not hand-edit.
#
# A change here means the SAME file and the SAME manifest must land in the
# sibling repo.  See docs/SHARED-ARTIFACTS.md.
"""


def digest(path: pathlib.Path) -> str:
    """Return the SHA-256 of *path*, newline-normalised.

    Normalising CRLF keeps a Windows checkout from reporting spurious drift on
    files nobody edited.
    """
    data = path.read_bytes().replace(b"\r\n", b"\n")
    return hashlib.sha256(data).hexdigest()


def current() -> dict[str, str]:
    """Map logical artifact name -> digest of this repo's copy."""
    out: dict[str, str] = {}
    for name, rel in sorted(_ARTIFACTS.items()):
        path = _REPO_ROOT / rel
        if not path.is_file():
            raise SystemExit(f"shared artifact missing: {rel}")
        out[name] = digest(path)
    return out


def recorded() -> dict[str, str]:
    """Parse the manifest into logical artifact name -> digest."""
    if not _MANIFEST.is_file():
        return {}
    out: dict[str, str] = {}
    for line in _MANIFEST.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        sha, _, name = line.partition("  ")
        if name:
            out[name.strip()] = sha.strip()
    return out


def render(hashes: dict[str, str]) -> str:
    body = "".join(f"{sha}  {name}\n" for name, sha in sorted(hashes.items()))
    return _HEADER + body


def check() -> int:
    """Compare live files against the manifest; return a process exit code."""
    live, saved = current(), recorded()
    if not saved:
        print("no manifest — run: python scripts/sync_shared_artifacts.py --update")
        return 1
    problems = []
    for name in sorted(set(live) | set(saved)):
        if name not in saved:
            problems.append(f"  {name}: not in the manifest")
        elif name not in live:
            problems.append(f"  {name}: in the manifest but not in _ARTIFACTS")
        elif live[name] != saved[name]:
            problems.append(
                f"  {name} ({_ARTIFACTS[name]}): changed\n"
                f"      manifest {saved[name][:16]}…\n"
                f"      on disk  {live[name][:16]}…"
            )
    if problems:
        print("shared artifacts do not match the manifest:")
        print("\n".join(problems))
        print(
            "\nThese files are byte-identical copies shared with the sibling repo.\n"
            "If the change is intended:\n"
            "  1. python scripts/sync_shared_artifacts.py --update\n"
            "  2. copy the same file AND the same manifest into the sibling repo\n"
            "See docs/SHARED-ARTIFACTS.md."
        )
        return 1
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--check", action="store_true", help="verify (exit 1 on drift)")
    g.add_argument("--update", action="store_true", help="rewrite the manifest")
    g.add_argument("--print", dest="show", action="store_true", help="print hashes")
    args = ap.parse_args()

    if args.check:
        return check()
    if args.show:
        sys.stdout.write(render(current()))
        return 0
    _MANIFEST.write_text(render(current()), encoding="utf-8")
    print(f"wrote {_MANIFEST.relative_to(_REPO_ROOT)}")
    return 0


if __name__ == "__main__":  # pragma: no cover - CLI entry point
    raise SystemExit(main())
